spring.application.name=logify

spring.datasource.url=jdbc:mysql://localhost:3306/logify_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret=9bK#7LmP@2xQvN8rT$5yHfZ1wA6eUcX9sD4gJ7kLpQ2mNxR8v
jwt.expiration=36000000